version: '3'
services:
  nextcloud:
    build: .
    volumes:
      - ./:/var/www/html
    ports: 
    - 8081:80
    environment:
      - PHP_EXTENSION_XDEBUG=1
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_enable=1 remote_autostart=1